# Generated by Django 5.1.4 on 2024-12-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_audiofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
