# Generated by Django 5.1.4 on 2024-12-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiopost',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='audiopost',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
