# Generated by Django 5.1.4 on 2024-12-27 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0009_remove_audiopost_audio_file_audiopost_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiopost',
            name='uploader',
        ),
        migrations.AddField(
            model_name='audiopost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='audio_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
